# Generated by Django 2.2 on 2020-07-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takeappointment',
            old_name='phone_number',
            new_name='m_phone_number',
        ),
    ]
